#!/bin/bash
#PBS -l select=1:ncpus=23:mpiprocs=23:nodetype=haswell_reg
#PBS -P CSCI1305
#PBS -q smp
#PBS -l walltime=01:00:00
#PBS -o /mnt/lustre/users/jdevilliers1/november2020/ppo_output/6_dec/ppo_cheetah_test_000.out
#PBS -e /mnt/lustre/users/jdevilliers1/november2020/ppo_output/6_dec/ppo_cheetah_test_000.err
#PBS -m abe
#PBS -M -redacted-
#PBS -S /bin/bash
source activate /home/jdevilliers1/earl
conda info --envs
conda list
cd /mnt/lustre/users/jdevilliers1/november2020
python bohb_ppo_mujoco_half_cheetah.py --n_processors 24 --shared_directory /mnt/lustre/users/jdevilliers1/november2020/ppo_output/6_dec/ --n_iterations 3
source deactivate
